# benchmark config yaml
### Please fill these accordingly
data_dir:
output_dir:
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_sql:

scheduler_file_path:
dask_profile: False

verify_results: False
verify_dir:

sheet: GPU-BDB Dask-SQL
tab: SF1K Dask-SQL
get_read_time: False
